<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GerkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gerks = [
            [
                "id" => 1,
                "name" => "Okoli hiše",
                "area" => 1567,
                "pid" => 4281901,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => 4,
                "type" => 1222,
                "block_id" => 1,
                "average_altitude" => 336.75,
                "average_slope_percentage" => 10,
                "average_exposition" => 201,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => "2023-10-08T07:34:40.000000Z",
                "updated_at" => "2023-10-08T07:34:40.000000Z"
            ],
            [
                "id" => 2,
                "name" => "Pri Baš",
                "area" => 21107,
                "pid" => 3321824,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => 4,
                "type" => 1131,
                "block_id" => 1,
                "average_altitude" => 1000,
                "average_slope_percentage" => 10,
                "average_exposition" => 180,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => "2023-10-08T07:34:40.000000Z",
                "updated_at" => "2023-10-08T07:34:40.000000Z"
            ],
            [
                "id" => 3,
                "name" => "Gornji laz",
                "area" => 3762,
                "pid" => 5435254,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => 2,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => "2023-10-08T07:34:40.000000Z",
                "updated_at" => "2023-10-08T07:34:40.000000Z"
            ],
            [
                "id" => 4,
                "name" => "Spodnji laz",
                "area" => 3804,
                "pid" => 5444879,
                "scheme_type" => "",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1100,
                "block_id" => 2,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => "2023-10-08T07:34:40.000000Z",
                "updated_at" => "2023-10-08T07:34:40.000000Z"
            ],
            [
                "id" => 5,
                "name" => "Spodnji laz",
                "area" => 142,
                "pid" => 5444913,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => 2,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => "2023-10-08T07:34:40.000000Z",
                "updated_at" => "2023-10-08T07:34:40.000000Z"
            ],
            [
                "id" => 6,
                "name" => "Spodnji laz",
                "area" => 738,
                "pid" => 6048538,
                "scheme_type" => "",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1131,
                "block_id" => 2,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => "2023-10-08T07:34:40.000000Z",
                "updated_at" => "2023-10-08T07:34:40.000000Z"
            ],
            [
                "id" => 7,
                "name" => "Pri kozolcu",
                "area" => 4841,
                "pid" => 5402010,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 8,
                "name" => "Podolnica",
                "area" => 4582,
                "pid" => 5435510,
                "scheme_type" => "",
                "is_pasture" => 0,
                "number_of_mowings" => null,
                "type" => 1100,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 9,
                "name" => "Brinovc",
                "area" => 1994,
                "pid" => 5435462,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 10,
                "name" => "Naravn",
                "area" => 1671,
                "pid" => 5427866,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 11,
                "name" => "Naravn",
                "area" => 2474,
                "pid" => 5427760,
                "scheme_type" => "",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1100,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 12,
                "name" => "Naravn",
                "area" => 2892,
                "pid" => 4578677,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 13,
                "name" => "Za cerkvijo",
                "area" => 1182,
                "pid" => 5435528,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 14,
                "name" => "Praprotnik",
                "area" => 1179,
                "pid" => 5435502,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 15,
                "name" => "Rešak",
                "area" => 3146,
                "pid" => 5427661,
                "scheme_type" => "",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1131,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 16,
                "name" => "Za hišo",
                "area" => 201,
                "pid" => 5435498,
                "scheme_type" => "",
                "is_pasture" => 0,
                "number_of_mowings" => null,
                "type" => 1100,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 17,
                "name" => "Sadovnjak ob hiši",
                "area" => 519,
                "pid" => 5893838,
                "scheme_type" => "EKST",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1222,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 18,
                "name" => "Spodnja njiva",
                "area" => 131,
                "pid" => 5435428,
                "scheme_type" => "",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1100,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 19,
                "name" => "Na Plunovem",
                "area" => 8193,
                "pid" => 5980230,
                "scheme_type" => "",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1100,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ],
            [
                "id" => 20,
                "name" => "Na Binetovem",
                "area" => 6398,
                "pid" => 6402389,
                "scheme_type" => "",
                "is_pasture" => 1,
                "number_of_mowings" => null,
                "type" => 1300,
                "block_id" => null,
                "average_altitude" => null,
                "average_slope_percentage" => null,
                "average_exposition" => null,
                "farm_id" => 1,
                "deleted_at" => null,
                "created_at" => null,
                "updated_at" => null
            ]
        ];

        foreach ($gerks as $gerk) {
            \App\Models\Gerk::query()->create($gerk);
        }

    }
}
